booking/urls.py
# Copyright 2021 Éclaireuses Éclaireurs de France, Gaël UTARD
#
# This file is part of Résa.
#
# Résa is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

from django.urls import path
from . import views


urlpatterns = [
    path('', views.BookingListView.as_view(), name='booking_list'),
    path('booking/<int:pk>/', views.BookingDetailView.as_view(), name='booking_detail'),
    path('booking/create/', views.BookingCreateView.as_view(), name='booking_create'),
    path('booking/<int:pk>/update/', views.BookingUpdateView.as_view(), name='booking_update'),
    path('booking/<int:pk>/sale_create/', views.BookingSaleCreateView.as_view(), name='booking_sale_create'),
    path('booking/<int:booking_pk>/item/create/<int:product_pk>/', views.BookingItemCreateView.as_view(),
         name='bookingitem_create'),
    path('bookingitem/<int:pk>/update/', views.BookingItemUpdateView.as_view(), name='bookingitem_update'),
    path('bookingitem/<int:pk>/delete/', views.BookingItemDeleteView.as_view(), name='bookingitem_delete'),
    path('booking.ics', views.CalendarFeed()),
    path('agreement/create/<int:booking_pk>/', views.AgreementCreateView.as_view(), name='agreement_create'),
    path('agreement/<int:pk>/', views.AgreementDetailView.as_view(), name='agreement_detail'),
    path('agreement/<int:pk>/delete/', views.AgreementDeleteView.as_view(), name='agreement_delete'),
    path('occupancy/', views.OccupancyView.as_view(), name='occupancy'),
    path('stats/', views.StatsView.as_view(), name='stats'),
    path('cotisations/', views.CotisationsView.as_view(), name='cotisations'),
    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('thirdparty-autocomplete/', views.ThirdPartyAutocomplete.as_view(), name='thirdparty-autocomplete'),
]

resa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oidc/', include('oauth2_authcodeflow.urls')),
    path('', include('members.urls')),
    path('', include('booking.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ]

booking/models.py
# Copyright 2021 Éclaireuses Éclaireurs de France, Gaël UTARD
#
# This file is part of Résa.
#
# Résa is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

from datetime import timedelta
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Case, F, Min, Max, Sum, When, Value, Q
from django.db.models.functions import Coalesce, ExtractDay, Concat, Least
from django.urls import reverse
from members.utils import current_year, today
from phonenumber_field.modelfields import PhoneNumberField
from accounting.models import Account, Analytic, ThirdParty


class Agreement(models.Model):
    date = models.DateField(verbose_name="Date")
    order = models.IntegerField(verbose_name="Numéro d'ordre")
    odt = models.FileField(upload_to='conventions', blank=True)
    pdf = models.FileField(upload_to='conventions', blank=True)
    booking = models.ForeignKey('Booking', verbose_name="Réservation", related_name='agreements',
                                on_delete=models.PROTECT)
    deadline = models.DateField(verbose_name="Date limite", blank=True, null=True)

    class Meta:
        verbose_name = "Convention"
        get_latest_by = 'date'
        ordering = ('order', )

    def number(self):
        return "{year}-{order:03}".format(year=self.booking.year, order=self.order)
    number.short_description = "Numéro"
    number.admin_order_field = Concat('booking__year', Value('-'), 'order')

    def __str__(self):
        return self.number()


class BookingState(models.Model):
    INCOME_CHOICES = (
        (1, "Potentiel"),
        (2, "Confirmé"),
        (3, "Facturé"),
        (4, "Infirmé"),
        (5, "Annulé"),
    )
    COLOR_CHOICES = (
        ('default', "Gris"),
        ('primary', "Bleu"),
        ('success', "Vert"),
        ('info', "Cyan"),
        ('warning', "Orange"),
        ('danger', "Rouge"),
    )
    title = models.CharField(verbose_name="Intitulé", max_length=100)
    income = models.IntegerField(verbose_name="Chiffre d'affaire", choices=INCOME_CHOICES)
    color = models.CharField(verbose_name="Couleur", max_length=10, choices=COLOR_CHOICES)
    ical = models.BooleanField(verbose_name="Dans l'agenda ICal", default=False)

    class Meta:
        verbose_name = "Statut"
        ordering = ('title',)

    def __str__(self):
        return self.title


class BookingManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.annotate(begin=Min('items__begin'), end=Max('items__end'))
        qs = qs.annotate(nights=ExtractDay(F('end') - F('begin')))
        qs = qs.annotate(headcount=Sum(Case(When(items__accomodation=True, then=F('items__headcount')))))
        qs = qs.annotate(headcount_cot=Sum(Case(When(
            Q(items__accomodation=True) & Q(items__price__gt=0),
            then=F('items__headcount')
        ))))
        days = ExtractDay(F('items__end') - F('items__begin'), output_field=models.DecimalField())
        overnights = Case(When(items__accomodation=True, then=days * F('items__headcount')))
        qs = qs.annotate(overnights=Sum(overnights))
        amount = Coalesce(
            F('items__price') *
            Case(
                When(items__per_night=True, then=days),
                default=Decimal(1)
            ) *
            Case(
                When(items__per_quantity=True, then=F('items__headcount')),
                default=Decimal(1),
                output_field=models.DecimalField()
            ) * Case(
                When(items__option=True, then=Value(0)),
                default=Value(1)
            ),
            Decimal(0)
        )
        sub_amount_cot = days * F('items__headcount')
        amount_cot = Case(
            When(
                Q(items__begin__lt='2023-11-01')
                & Q(items__accomodation=True)
                & ~Q(org_type__in=(Booking.OrgType.BECOURS, Booking.OrgType.EEDF)),
                then=sub_amount_cot
            ),
            When(
                Q(items__begin__gte='2023-11-01')
                & Q(items__price__gt=0)
                & Q(items__accomodation=True)
                & Q(org_type__in=(Booking.OrgType.SF, Booking.OrgType.SE, Booking.OrgType.SCHOOL)),
                then=F('items__headcount') * Decimal(3)
            ),
            When(
                Q(items__begin__gte='2023-11-01')
                & Q(items__price__gt=0)
                & Q(items__accomodation=True)
                & Q(org_type__in=(Booking.OrgType.ASSO, Booking.OrgType.PRIVATE)),
                then=F('items__headcount') * Decimal(5)
            ),
        )
        qs = qs.annotate(amount_cot=Least(Coalesce(Sum(amount_cot), Decimal(0)), Decimal(300)))
        qs = qs.annotate(amount=Coalesce(Sum(amount), Decimal(0)) + F('amount_cot'))
        qs = qs.annotate(amount_deposit=F('amount') * F('deposit') / Decimal(100))
        return qs


class Booking(models.Model):
    class OrgType(models.IntegerChoices):
        BECOURS = 7, "Bécours"
        EEDF = 1, "EEDF"
        SF = 2, "Scouts français"
        SE = 3, "Scouts étrangers"
        ASSO = 4, "Association"
        SCHOOL = 6, "Scolaires/ALSH"
        PRIVATE = 5, "Particulier"

    title = models.CharField(verbose_name="Intitulé", max_length=100, blank=True)
    year = models.IntegerField(verbose_name="Année", default=current_year)
    org_type = models.IntegerField(verbose_name="Type d'organisation", choices=OrgType.choices, blank=True, null=True)
    structure = models.CharField(verbose_name="Structure", max_length=100, blank=True)
    contact = models.CharField(verbose_name="Contact", max_length=100, blank=True)
    stay_contact = models.CharField(verbose_name="Contact du séjour", max_length=100, blank=True)
    email = models.EmailField(verbose_name="Email", blank=True)
    tel = PhoneNumberField(verbose_name="Téléphone", blank=True)
    state = models.ForeignKey(BookingState, verbose_name="Statut", blank=True, null=True, on_delete=models.PROTECT)
    description = models.TextField(verbose_name="Description", blank=True)
    signed_agreement = models.OneToOneField(Agreement, verbose_name="N° convention signée", blank=True, null=True,
                                            related_name='signedx_booking', on_delete=models.PROTECT)
    signed_agreement_scan = models.FileField(verbose_name="Scan convention signée", upload_to='conventions_signees',
                                             blank=True)
    insurance_scan = models.FileField(verbose_name="Attestation d'assurance", upload_to='assurance', blank=True)
    invoice = models.FileField(verbose_name="Facture", upload_to='factures', blank=True)
    invoice_number = models.CharField(max_length=10, blank=True)
    preferred_place = models.CharField(verbose_name="Placement souhaité", max_length=1024, blank=True)
    wood = models.CharField(verbose_name="Bois", max_length=1024, blank=True)
    exclusivity = models.BooleanField(verbose_name="Exclusivité", default=False)
    deposit = models.IntegerField(verbose_name="Arrhes (%)", default=30,
                                  validators=[MinValueValidator(0), MaxValueValidator(100)])
    thirdparty = models.ForeignKey(ThirdParty, verbose_name="Tiers", null=True, blank=True, on_delete=models.PROTECT)

    objects = BookingManager()

    class Meta:
        verbose_name = "Réservation"
        ordering = ('-year', 'title')

    def __str__(self):
        return "{} - {}".format(self.year, self.title)

    def get_absolute_url(self):
        return reverse('booking_detail', kwargs={'pk': self.pk})

    @property
    def cot_rate(self):
        if self.org_type in (self.OrgType.SF, self.OrgType.SE, self.OrgType.SCHOOL):
            return Decimal('3.00')
        if self.org_type in (self.OrgType.ASSO, self.OrgType.PRIVATE):
            return Decimal('5.00')
        return 0

    @property
    def overdue(self):
        if self.state.income != 1:
            return False
        agreement = self.agreement
        if not agreement:
            return False
        return agreement.deadline < today()

    @property
    def tel_display(self):
        if not self.tel:
            return ''
        elif self.tel.country_code == 33:
            return self.tel.as_national
        else:
            return self.tel.as_international

    @property
    def terrain(self):
        return self.items.filter(product=1).exists()

    @property
    def village(self):
        return self.items.filter(product=2).exists()

    @property
    def agreement(self):
        agreements = list(self.agreements.all())
        if not agreements:
            return None
        agreements.sort(key=lambda agreement: agreement.date, reverse=True)
        return agreements[0]

    @property
    def payment(self):
        return sum([payment.amount for payment in self.payments.all()])

    @property
    def balance(self):
        if self.amount is None and self.payment is None:
            return None
        return (self.amount or 0) - (self.payment or 0)

    @property
    def gone(self):
        return bool(self.end) and self.end < today()

    @property
    def google_id(self):
        return 'jeito{}'.format(self.id)

    @property
    def google_repr(self):
        begin = min([date for date in self.items.values_list('begin', flat=True) if date], default=None)
        end = max([date for date in self.items.values_list('end', flat=True) if date], default=None)
        if not begin or not end:
            return None
        return {
            'id': self.google_id,
            'summary': self.title + (' ?' if self.state.income == 1 else ''),
            'start': {
                'date': begin.isoformat(),
            },
            'end': {

booking/templates/booking/agreement_confirm_delete.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

	<h1>Supprimer la convention {{ agreement }} ?</h1>

    <div class="alert alert-warning">
        ATTENTION ! Ne pas supprimer une convention si elle a déjà été transmise aux usagers.
    </div>

	<p>Oui, je suis sûr de vouloir supprimer la convention <b>{{ agreement }}</b> pour la réservation <b>{{ agreement.booking.title }}</b>.</p>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<a href="{% url 'booking_detail' agreement.booking.pk %}" class="btn btn-primary">Annuler</a>
		<input type="submit" value="Supprimer" class="btn btn-danger">
	</form>

</div>

{% endblock content %}

booking/templates/booking/agreement_form.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

	<h1>Créer une convention pour {{ booking.title }}</h1>

	<form method="POST" enctype="multipart/form-data">
        {% crispy form %}
		<a href="{% url 'booking_detail' booking.pk %}" class="btn btn-default">Annuler</a>
		<input type="submit" value="Créer" class="btn btn-primary">
	</form>

</div>

{% endblock content %}

booking/templates/booking/base.html
{% extends 'base.html' %}

{% block menu %}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        Usagers
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a href="{% url 'booking_list' %}">Réservations</a>
        </li>
        <li>
            <a href="{% url 'occupancy' %}">Occupation</a>
        </li>
        <li>
            <a href="{% url 'stats' %}">Statistiques</a>
        </li>
        <li>
            <a href="{% url 'cotisations' %}">Cotisations</a>
        </li>
        <li>
            <a href="{% url 'product_list' %}">Produits</a>
        </li>
    </ul>
</li>

{% endblock %}

booking/templates/booking/booking_detail.html
{% extends 'booking/base.html' %}

{% block content %}

<div class="container">

    {% if perms.booking.change_booking %}
        <div class="btn-toolbar title-action">
            <a href="{% url 'booking_update' booking.pk %}" class="btn btn-primary">
                <span class="glyphicon glyphicon-edit"></span>
                Modifier
            </a>
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-plus"></span> Produit <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    {% for product in products %}
                        <li><a href="{% url 'bookingitem_create' booking.pk product.pk %}">{{ product }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <a href="{% url 'agreement_create' booking.pk %}" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span> Convention
            </a>
            {% if booking.end %}
                <a href="{% url 'booking_sale_create' booking.pk %}" class="btn btn-default">
                    <span class="glyphicon glyphicon-euro"></span> Facturer
                </a>
            {% endif %}
        </div>
    {% endif %}

    <h1>{{ booking.title }}</h1>

    <table class="table table-striped table-hover table-condensed">
        <tr>
            <th>Statut</th>
            <td><span class="label label-{{ booking.state.color }}">{{ booking.state.title }}</span></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Structure</th>
            <td>{{ booking.structure }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Type d'organisation</th>
            <td>{{ booking.get_org_type_display }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Contact</th>
            <td>{{ booking.contact }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Contact du séjour</th>
            <td>{{ booking.stay_contact }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><a href="mailto:{{ booking.email }}">{{ booking.email }}</a></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Tél.</th>
            <td>{{ booking.tel_display }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Tiers</th>
            <td>{{ booking.thirdparty|default:"" }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Dates</th>
            <td>Du {{ booking.begin|date:'D d/m/y' }} au {{ booking.end|date:'D d/m/y' }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Nuits</th>
            <td>{{ booking.nights|default_if_none:"" }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Effectif</th>
            <td>{{ booking.headcount|default_if_none:"" }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Nuitées</th>
            <td>{{ booking.overnights|default_if_none:"" }}</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Exclusivité</th>
            <td>{{ booking.exclusivity|yesno }}</td>
            <td></td>
            <td></td>
        </tr>
        {% if booking.preferred_place %}
            <tr>
                <th>Placement souhaité</th>
                <td>{{ booking.preferred_place }}</td>
                <td></td>
                <td></td>
            </tr>
        {% endif %}
        {% if booking.wood %}
            <tr>
                <th>Bois</th>
                <td>{{ booking.wood }}</td>
                <td></td>
                <td></td>
            </tr>
        {% endif %}
        {% for item in items %}
            <tr>
                <th>
                    {{ item.title }}
                    {% if item.option %}(option){% endif %}
                </th>
                <td>
                    {% if item.price %}{{ item.price|floatformat:2 }} €{% endif %}
                    {% if item.price and item.per_quantity %}×{% endif %}
                    {% if item.per_quantity and item.headcount %}{{ item.headcount }} {{ item.pretty_unit }}{% endif %}
                    {% if item.price or item.per_quantity %}{% if item.per_night %}×{% endif %}{% endif %}
                    {% if item.per_night %}{{ item.nights }} nuits (du {{ item.begin|date:'D d/m/y' }} au {{ item.end|date:'D d/m/y' }}){% endif %}
                </td>
                <td class="text-right">
                    {% if item.price %}
                        {% if item.option %}
                            ({{ item.amount|floatformat:2 }} €)
                        {% else %}
                            {{ item.amount|floatformat:2 }} €
                        {% endif %}
                    {% else %}
                        offert
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'bookingitem_delete' item.pk %}">
                        <span class="glyphicon glyphicon-trash text-danger"></span>
                    </a>
                    &nbsp;
                    <a href="{% url 'bookingitem_update' item.pk %}">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                </td>
            </tr>
        {% endfor %}
        <tr>
            <th>Cotisation</th>
            <td>
                {% if booking.amount_cot == 300 %}
                    forfait
                {% elif booking.cot_rate %}
                    {{ booking.cot_rate }} € × {{ booking.headcount_cot }} personnes
                {% endif %}
            </td>
            <td class="text-right">{{ booking.amount_cot|floatformat:2 }} €</td>
            <td></td>
        </tr>
        <tr>
            <th>Montant total</th>
            <td></td>
            <td class="text-right">{% if booking.amount %}{{ booking.amount|floatformat:2 }} €{% endif %}</td>
            <td></td>
        </tr>
        <tr>
            <th>Arrhes</th>
            <td></td>
            <td class="text-right">{% if booking.amount_deposit %}{{ booking.amount_deposit|floatformat:2 }} €{%  endif %}</td>
            <td></td>
        </tr>
        {% for payment in booking.payments.all %}
        <tr>
            <th>Paiement</th>
            <td>{{ payment.get_mean_display }} le {{ payment.date|date:'d/m/y' }}{% if payment.scan %} (<a href="{{ payment.scan.url }}">télécharger</a>){% endif %}</td>
            <td class="text-right">{{ payment.amount|floatformat:2 }} €</td>
            <td></td>
        </tr>
        {% endfor %}
        <tr>
            <th>Solde</th>
            <td></td>
            <td class="text-right">{% if booking.balance is not None %}{{ booking.balance|floatformat:2 }} €{%  endif %}</td>
            <td></td>
        </tr>
        {% for agreement in booking.agreements.all %}
            <tr>
                <th>Convention</th>
                <td>
                    {% if agreement.pdf %}<a href="{{ agreement.pdf.url }}">{{ agreement.number }} (PDF)</a>{% endif %}
                    {% if agreement.odt %}(<a href="{{ agreement.odt.url }}">éditer</a>){% endif %}
                </td>
                <td></td>
                <td>
                    <a href="{% url 'agreement_delete' agreement.pk %}">
                        <span class="glyphicon glyphicon-trash text-danger"></span>
                    </a>
                </td>
            </tr>
        {% endfor %}
        {% if booking.signed_agreement or booking.signed_agreement_scan %}
            <tr>
                <th>Convention signée</th>
                <td>
                    {% if booking.signed_agreement_scan %}<a href="{{ booking.signed_agreement_scan.url }}">{% endif %}
                    {{ booking.signed_agreement.number|default:"Télécharger" }}
                    {% if booking.signed_agreement_scan %}</a>{% endif %}
                </td>
                <td></td>
                <td></td>
            </tr>
        {%  endif %}
        {% if booking.insurance_scan %}
            <tr>
                <th>Attestation d'assurance</th>
                <td><a href="{{ booking.insurance_scan.url }}">télécharger</a></td>
                <td></td>
                <td></td>
            </tr>
        {% endif %}
        {% if booking.invoice or booking.invoice_number %}
            <tr>
                <th>Facture</th>
                <td>
                    {% if booking.invoice %}<a href="{{ booking.invoice.url }}">{% endif %}{{ booking.invoice_number|default:"télécharger" }}{% if booking.invoice %}</a>{% endif %}
                </td>
                <td></td>
                <td></td>
            </tr>
        {% endif %}
        {% if booking.description %}
            <tr>
                <th>Description</th>
                <td colspan="3">
                    {{ booking.description|linebreaks }}
                </td>
            </tr>
        {% endif %}
    </table>

    <a href="{% url 'booking_list' %}" class="btn btn-default">Retour</a>

</div>

{% endblock content %}

booking/templates/booking/booking_form.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

    <h1>{% if booking %}{{ booking.title }}{% else %}Nouvelle réservation{% endif %}</h1>

    <form method="POST" enctype="multipart/form-data">
        {% crispy form %}
        <input type="submit" name="create" value="Enregistrer" class="btn btn-primary">
    </form>

</div>

{% endblock content %}

booking/templates/booking/booking_list.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">

    {% if perms.booking.add_booking %}
        <a href="{% url 'booking_create' %}" class="btn btn-primary title-action">Ajouter</a>
    {% endif %}
    <h1>Réservations</h1>

    {% crispy filter.form %}

    <table class="table table-striped table-hover">
        <tr>
            <th>Intitulé</th>
            <th>Statut</th>
            <th class="text-right">Du <span class="glyphicon glyphicon-chevron-down"></span></th>
            <th class="text-right">Au</th>
            <th class="text-right">Nuits</th>
            <th class="text-right">Effectif</th>
            <th class="text-right">Nuitées</th>
            <th class="text-right">Montant</th>
            <th class="text-right">Solde</th>
            <th>Convention</th>
            <th>Date limite</th>
        </tr>
        {% for booking in booking_list %}
            <tr {% ifchanged booking.gone %}class="separator"{% endifchanged %}>
                <td><a href="{{ booking.get_absolute_url }}">{{ booking.title }}</a></td>
                <td><span class="label label-{{ booking.state.color }}">{{ booking.state.title }}</span></td>
                <td class="text-right">{{ booking.begin|date:'D d/m/y' }}</td>
                <td class="text-right">{{ booking.end|date:'D d/m/y' }}</td>
                <td class="text-right">{{ booking.nights|default_if_none:"" }}</td>
                <td class="text-right">{{ booking.headcount|default_if_none:"" }}</td>
                <td class="text-right">{{ booking.overnights|default_if_none:"" }}</td>
                <td class="text-right">{% if booking.amount %}{{ booking.amount|floatformat:2 }} €{% endif %}</td>
                <td class="text-right">{% if booking.balance %}{{ booking.balance|floatformat:2 }} €{%  endif %}</td>
                <td>
                    {%  if booking.agreement and booking.agreement.pdf %}
                        <a href="{{ booking.agreement.pdf.url }}">{{ booking.agreement.number }}</a>
                    {% endif %}
                </td>
                <td>
                    {% if booking.state.income == 1 %}
                        <span {% if booking.overdue %}style="color: red;"{% endif %}>{{ booking.agreement.deadline|date:"d/m/Y" }}</span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td></td>
            <td class="text-right"></td>
            <td class="text-right"></td>
            <td class="text-right"></td>
            <td class="text-right">{{ headcount }}</td>
            <td class="text-right">{{ overnights }}</td>
            <td class="text-right">{{ amount|floatformat:2 }} €</td>
            <td class="text-right">{{ balance|floatformat:2 }} €</td>
            <td></td>
        </tr>
        <tr class="total">
            <td>Total hors Bécours</td>
            <td></td>
            <td class="text-right"></td>
            <td class="text-right"></td>
            <td class="text-right"></td>
            <td class="text-right">{{ headcount_ext }}</td>
            <td class="text-right">{{ overnights_ext }}</td>
            <td class="text-right">{{ amount_ext|floatformat:2 }} €</td>
            <td class="text-right">{{ balance_ext|floatformat:2 }} €</td>
            <td></td>
        </tr>
    </table>

</div>

{% endblock content %}


{% block js %}

    {{ block.super }}

    <script>
        $('select, :checkbox').change(function() {$('#filter').submit()});
    </script>

{% endblock js %}

booking/templates/booking/bookingitem_confirm_delete.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

	<h1>Supprimer {{ bookingitem }} ?</h1>

	<p>Oui, je suis sûr de vouloir supprimer le produit <b>{{ bookingitem }}</b> de la réservation <b>{{ bookingitem.booking.title }}</b>.</p>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<a href="{% url 'booking_detail' bookingitem.booking.pk %}" class="btn btn-primary">Annuler</a>
		<input type="submit" value="Supprimer" class="btn btn-danger">
	</form>

</div>

{% endblock content %}

booking/templates/booking/bookingitem_form.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">

    <h1>{% if bookingitem %}{{ bookingitem }}{% else %}Ajouter {{ product }} à {{ booking.title }}{% endif %}</h1>

    <form method="POST" enctype="multipart/form-data">
        {% crispy form %}
        <input type="submit" name="create" value="Enregistrer" class="btn btn-primary">
    </form>

</div>

{% endblock content %}